 [[Oxide dispersion-strengthened steels: A comparison of some commercial and experimental alloys - ScienceDirect]] [Oxide dispersion-strengthened steels: A comparison of some commercial and experimental alloys - ScienceDirect] (https://www.sciencedirect.com/science/article/pii/S0022311505000176)

## Abstract
Oxide dispersion-strengthened (ODS) steels are being developed and investigated for nuclear fission and nuclear fusion applications in Japan, Europe, and the United States. In addition, commercial ODS products are available and have been used in niche applications. Microstructural and mechanical properties studies have been conducted at Oak Ridge National Laboratory and elsewhere on various commercial and experimental ODS steels. Tensile and creep properties have been obtained and collected from literature and commercial sources. These data are compared to show the differences and similarities of different ODS steels, and observations are explained in terms of the microstructures of the steels.

|Element⁎| 12Y1 |12YWT | MA956 |MA957 | PM 2000|
|------|------|------|------|------|------|
|C | 0.045 |0.050 | 0.03|0.030 |0.01|
|Mn|0.04|0.60|0.06|0.09|0.11|
|P|<0.001|0.019|0.008|0.007|<0.002|
|S|0.002|0.005|0.005|0.006|0.0021|
|Si|0.03|0.18|0.05|0.04|0.04|
|Ni|0.24|0.27|0.11|0.13|0.01|
|Cr||12.85|12.58|21.7|13.7|18.92|
|Mo|0.03|0.02|<0.05|0.30|0.01|
V
0.007
0.002



Ti
0.003
0.35
0.33
0.98
0.45
Co
0.005
0.02
0.03

0.01
Cu
0.01
0.02


0.01
Al
0.007

5.77
0.03
5.10
B
0.004


0.0009
<0.0003
W
<0.01
2.44


0.04
Zr
0.003



<0.01
N
0.017
0.014
0.029
0.044
0.0028
O
0.15
0.16
0.21
0.21
0.25
Y
0.20
0.16
0.38
0.28
0.37
